### PR TITLE
Replace ActionBar with Toolbar and NavigationView

### PR DESCRIPTION
**Pull request by staceybellerose**
Resolves issue #38

### CODE REVIEW

**Comment by hissingpanda** [comment]
Sorry for just getting to this now! But wow this looks great, thanks so much! The material design is fantastic, and the direction button is way more intuitive. Also appreciate the code cleanup. 

There were a few issues I noticed though:
- [ ] Bottom info bar margin is a bit low, where the title looks kind of cut off. And when no bathroom is selected (no gps enabled) a blank white line shows
- [ ] Bottom info bar is still accessible from the add a bathroom and feedback pages
- [ ] Google maps button is cut off in the info window on a Nexus 5 emulator, also if we're removing the icon, maybe we can just have the string say "open in maps"

The last one could just be because of the text size on the emulator, as it displayed fine on my physical Moto X. I've attached some screenshots so you can see what I mean. 

screen shot 2017-02-03 at 16 48 16
screen shot 2017-02-03 at 17 01 34

**Comment by staceybellerose** [comment]
I'm glad you like the enhancements that I made. I'll take a look at the issues that you brought up and update the code. I'm working on more enhancements as well.

**Comment by hissingpanda** [comment]
I think i'm going to try to finish this up on monday at the hackathon. https://www.eventbrite.com/e/refuge-restrooms-hack-night-tickets-32423804472

**Comment by hissingpanda** [comment]
Just pushed this live in release v.1.4. Should be on the google play store in a few hours. Thanks so much for this PR!

**Pull request merged**
