### PR TITLE
Migrate to current map API

### PR DESCRIPTION
**Pull request by davidmascharka**
Addresses most of #19 

Changes everything over from using the older v2 maps to using android.gms maps. Also fixes up some crashes I had getting `NullPointerException`s in a few places.

### CODE REVIEW

**Comment by hissingpanda** [comment]
This is great! Thanks so much! I know there have been a few users who have been unable to open the app due to the map crashing from a nullpointer exception right away. I think this should solve that.

Two minor issues I noticed:

1. This seems to bring back a similar issue to #7; you can see what I mean if you search for "Cafe Depot". This is probably related to switching the BathroomInfoWindow to be its own class, which is totally great and something we should do.
2. Just a minor styling tweak, when the bathroom is accessible and unisex, the unisex symbol expands the height of the info window making it unnecessarily large. Before I think I had pushed up the accessible symbol to be in line with the title to make it look a little better.

I'll see if I have time this week to take care of these. Once that's done, I'll merge and push out a new update!

**Comment by davidmascharka** [comment]
Thanks for catching those.

1. For whatever reason, passing the decoded string into the InfoWindow class broke it so I pass the encoded string, then decode in the InfoWindow right before I set the title. It works for the "Cafe Depot" example now.

2. Added some negative padding to fix that problem.

**Comment by hissingpanda** [comment]
Meant to commit to this before merging... I edited a few things.

1. This was also occurring in the address field, and in the detailed info window. I ended up having to get the string redundantly from utf-8 which was weird. But it's all working now.
2. This looks great now!

There also seems to be a large amount of gradle errors now (968). Here's a few examples, it just cycles like this:
	AGPBI: {"kind":"error","text":"warning: Ignoring InnerClasses attribute for an anonymous inner class","sources":[{}]}
	AGPBI: {"kind":"error","text":"(freemarker.template.utility.XmlEscape$1) that doesn\u0027t come with an","sources":[{}]}

It seems to be from the FreeMarker library. What is this being used for exactly? The build is also erroring out. "the Gradle daemon needs a larger heap", which might be on my end.

**Comment by davidmascharka** [comment]
I actually have no idea what the FreeMarker library is for. I noticed my build was failing on TravisCI because I didn't have it in the libs folder. I assumed it was integrated somewhere else in the project. It's probably a good idea to try removing it and see if it breaks anything. I'm not familiar with TravisCI so I'm not sure what it's looking for exactly.

**Comment by hissingpanda** [comment]
Ok cool. I'll remove that then and see what's going on in Travis. Thanks again for the PR!

**Comment by hissingpanda** [comment]
Removed as of fadbbaf. Build No. 22 is passing.

**Pull request merged**
