### PR TITLE
Open Restroom in Google Maps

### PR DESCRIPTION
**Pull request by davidmascharka**
Added functionality to open a restroom in Google Maps from the detailed `InfoViewFragment`

### CODE REVIEW

**Comment by hissingpanda** [comment]
It looks like you left a merge conflict in strings.xml: 
```
<<<<<<< HEAD
 +=======
```

This looks great though! I'll check it out in a bit.

**Comment by hissingpanda** [comment]
This works great. One quirk is that the button overlaps restrooms with long comments, making the comments unreadable. Search "Al Taib" to see what I mean. Not sure why, both views have margins in place..

**Comment by davidmascharka** [comment]
Thanks! I hadn't tried on a lower resolution device so I didn't run into that problem. Made a galaxy nexus emulator and fixed that up with some layout changes.

**Comment by hissingpanda** [comment]
I noticed one more thing: when you rotate to a horizontal screen, the scrollview for directions and comments just disappears, at least on a Moto X 2nd gen. You can't scroll or see the text at all. I haven't really been focused on making the app responsive, never really tested it on a tablet, so this isn't a huge issue for me but... maybe it would be better if the open in maps button was just the google maps icon, and it was up by the accessible and unisex icons or something? This would be less intuitive though. I also think adding the button below makes the scrollview pretty small on some devices. 

Let me know what you think. I'm also open to just merging as is and pushing it in the next update just to see the feedback we get.

**Comment by davidmascharka** [comment]
You're right, that's definitely a problem in landscape mode and I'm sure in low-resolution devices too. I went ahead and switched it up to the Maps icon in the heading across from the close button. I think it looks like a reasonable solution at least for now.

**Comment by hissingpanda** [comment]
LGTM! I'll try to push this as an update to the app tonight

**Pull request merged**
