### PR TITLE
Recent bathrooms

### PR DESCRIPTION
**Pull request by Sifrazooy**
### This update include the following:

- Removed old HTTP requests and replaced it with Volley.
- Updated the support library to version  23.1.1
- Updated the Server class to coupe with the changes.
- Used GreenDao   to save all of the request restrooms and user would be able to show them on map. 
- Added show recent restaurants, so the user could show the offline stored restrooms.

### Testing:
- I created a local ruby server to make sure the restrooms do appear to the user and saved correctly. 

### References:
* [GreenDao Tutorial](http://www.devteam83.com/en/tutorial-greendao-from-scratch-part-1/) 
*  [GreenDao Source ](https://github.com/greenrobot/greenDAOl)

### CODE REVIEW

**Comment by hissingpanda** [comment]
Wow this all looks great! Thanks so much! Big performance boost; thanks for switching the API call to Volley. And offline restrooms has been a re-occurring topic in the feedback. Nice to have that now. 

One question before I merge.. is there a way to set a query limit to the GreenDao database? Or a max storage size? After about 6 searches, my Moto X2 crashed when viewing 'Recent Bathrooms' because of the memory usage of the app trying to display 500+ restrooms. The database is never cleared upon closing the app, unless you manually clear the data, so, my understanding is that the amount of restrooms displayed will keep increasing ad infinitum as the user continues to use it each day. I'm wondering if we could limit the amount that is displayed when selecting to view recent bathrooms, or if we could just drop anything past the 200 most recent objects from the table. It looks like there's a query limit property in the [QueryBuilder class](http://greenrobot.org/javadoc/greendao/de/greenrobot/dao/QueryBuilder.html).

Thoughts?

**Comment by Sifrazooy** [comment]
Of coarse we can integrate a max limit, but I would prefer if you could send me a location that you have used to get 500+ restrooms so, I could regenerate the error or a local database you have used.

**Comment by hissingpanda** [comment]
There's a max of 75 restrooms per search, so it wasn't a single search that caused it, but multiple. If you search for several cities in a row (New York, Montreal, Chicago, Portland...) you can see that selecting the recent bathrooms option causes a slowdown and in my case, froze the app and my phone because of memory usage. 

The locations are stored permanently, so I think this would become a problem for users performing several different searches over the course of a month. That's why I think we should set a limit, or only show like the last 2 recent searches.

**Comment by hissingpanda** [comment]
In #16 the app now only loads the 150 most recently added restrooms based on a new timestamp property in the schema, and it also removes the recent restrooms from view when you enter a new search.

**Pull request merged**
