### PR TITLE
App now targets API 28.

### PR DESCRIPTION
**Pull request by Carmen-Git-It**
Replaced deprecated methods, updated to newest versions of volley and all other dependencies except for greendao.

### CODE REVIEW

**Comment by Carmen-Git-It** [comment]
My bad! Accidentally closed the pull request.

**Comment by DeeDeeG** [comment]
I made a commit on my personal fork of this project, showing approximately how .travis.yml could be updated so the tests can run on this pull request's updates. (I copied and pasted this from the Travis CI documentation, so the SDK versions and API level numbers are probably wrong.)

https://github.com/DeeDeeG/refugerestrooms-android/commit/9c537277cfccf51380bb4d8f89d8e1a12827a4a7

**Comment by Carmen-Git-It** [comment]
Thank you! Travis Cl is new to me as you can likely tell, I'll fix it ASAP. I figured that there would be growing pains with my first pull request.

Again, thank you!

**Comment by DeeDeeG** [comment]
No problem.

Side note: I'm not aware how import the Travis system is / isn't to @hissingpanda, who will likely be in charge of really reviewing this and merging. Just wanted to do any basic review I could manage to do as a mostly-not-familiar-with-Android person.

About what Travis does/ how it works:

Basically what Travis CI is doing is starting a virtual machine or "container," installing stuff needed to compile this app, and then compiling it to see there are no errors. (I'm not familiar with this repo enough to say if there are more tests run besides "does it compile?", but maybe there are other tests also.)

Doing this automatically is nice to make reviews easier, increase confidence in the code, etc. Makes it easier to find every bug... or at least more than without any Continuous Integration approach.

(Travis uns any time commits are added in a pull request here, or any time commits are added in any branch directly in this repository (excluding forks of this repo, like my or your fork for example.))

---

About this error:

I think we just need to update the stuff Travis installs on its virtual machine before compiling; Probably just adjust the API and tools version numbers to match what the tools versions are updated to in this pull request.

I would be happy to (attempt to) do this, give hints/help as needed, and/or be just as happy to leave it as a learning experience for you. Whatever works best. And hopefully @hissingpanda can give some comments on the actual code when they get some free time.

Best,

\- DeeDeeG

**Comment by DeeDeeG** [comment]
That sounds odd! I'll go look it up, but maybe there is nothing we can do about it for now? Thanks for the info.

**Comment by DeeDeeG** [comment]
If this does end up being an issue with Travis CI being uncooperative, and if manual testing shows the app is fine, then we will have a tradeoff between having any automated testing vs targeting an up-to-date API.

I would not presume what is right here, and I definitely defer to those more experienced with Android, but my gut says a working app with up-to-date code might be more important than having Travis CI passing. But again, I will definitely leave this to other folks to see what they want to do.

In the mean-time I will try and be of whatever help I can be to make Travis run without errors. I may not be much help, but I'll still look into it.

**Comment by Carmen-Git-It** [comment]
Thank you for the help! But I figured out how to make it pass travis-ci. Just had to write a new application test and run the emulator on Android 22 :)

On the bright side, I now understand Travis extremely well haha.

**Comment by Carmen-Git-It** [comment]
Issues #61 #58 #50 #47 #46 have been solved as of this series of commits (pending broader testing of course). 

I promise that this time I'll ACTUALLY be taking a break from pushing more commits to this.

I want to spend some time actually making sure every file is well-commented, and refactoring the code to align better with Google standards.

**Comment by DeeDeeG** [comment]
@Carmen-Git-It thanks for this!

---

@hissingpanda if it would make a difference, I could try to get these changes merged into a "staging" branch, and that would make it a little more organized where all these changes would end up... As in, it would make it possible to break future work up into additional, separate pull requests at this repo.

Basically I think targeting API level 28 is going to be a foundation for any future work, so other pull requests would need to be based off of these commits one way or another.

At the same time, if all this work is being submitted by one contributor (@Carmen-Git-It), and it all needs to work together seamlessly, it may make just as much sense to keep it all in one branch until merging into our `master` branch...

But overall, if you'd like to delegate some merging / pull request wrangling duty, I could do my best to herd this into a few smaller pull requests targeting a staging ("API 28") branch in this repo, and such.

In any case, hope all is well, and hopefully there will be a good opportunity to review these changes.

Best regards,

\- DeeDeeG

**Comment by DeeDeeG** [comment]
Here's my plan:

I want to leave at least another weekend in case @hissingpanda gets a chance to look at this soon.

Beyond that, I would start by having the "API 28" commits here in a branch. (perhaps this Pull Request can be pared back and redirected to the staging branch?; folks with "maintainer" status at of a GitHub repo, such as me, can redirect a pull request to any branch. So I'd just make the staging branch be identical to master, and then redirect/merge this Pull Request onto the new staging branch.)

(I suppose it would be up to and including this commit: https://github.com/RefugeRestrooms/refugerestrooms-android/pull/60/commits/9d23d7d01c084826b74a67d95fca94ff13350af1)

I do want to leave the `master` branch of this repo as-is for the time being, but we can always "fast-forward" master to the tip of the staging branch if we're ready to add that work to `master`.

Then the additional commits can be either one big pull request (onto that staging branch for now), or broken up however makes sense. (I don't really know Android code (for instance, would all these changes produce massive merge conflicts if one tried to separate them out?), so I will leave that call to someone who knows Android better.)

Hopefully this plan:

- Keeps things clean and organized
- Makes this as easy as possible to review when time comes up
- Gets this code closer to this repo's `master`.

However, at any time if @hissingpanda has a difference of opinion, I defer to their judgment, since I've never done any commits/anything besides open issues at this repo, and I don't want to impose.

**Comment by Carmen-Git-It** [comment]
Yep the rollback commit would definitely be https://github.com/RefugeRestrooms/refugerestrooms-android/commit/9d23d7d01c084826b74a67d95fca94ff13350af1 for a base-level API 28 version of the master.

Commits https://github.com/RefugeRestrooms/refugerestrooms-android/pull/60/commits/83facc5e9d9784488fb6b6b1254e39dd7ff4da97 to https://github.com/RefugeRestrooms/refugerestrooms-android/pull/60/commits/a4b9c164ed10bd7357429484c9cee1399973e442 could be a their own stable branch for sure, https://github.com/RefugeRestrooms/refugerestrooms-android/pull/60/commits/99b7369378604436a70497fad7b95f18c810dfce is a stable branch on its own, and https://github.com/RefugeRestrooms/refugerestrooms-android/pull/60/commits/555694fddbfb60490b3a2535987f6dd257a4d003 to https://github.com/RefugeRestrooms/refugerestrooms-android/pull/60/commits/7daff9bc4dd5069d4c6cdf84e68570b662457e07 are also a stable branch.

Most of the changes have an impact on one file in particular: [MainActivity.java](https://github.com/RefugeRestrooms/refugerestrooms-android/blob/master/app/src/main/java/org/refugerestrooms/views/MainActivity.java). I've tested various orders of branching and merging over the last hour or so and they all work with minimal conflicts to resolve aside from this one file, and even then the conflicts are simple to resolve. Splitting into 4 branches: master (API 28), location services, addBathroom pre-loading, and bottom sheet fixes; seems like the best way to go. They can all function separately or in tandem, with only a few easily resolvable conflicts in [MainActivity.java](https://github.com/RefugeRestrooms/refugerestrooms-android/blob/master/app/src/main/java/org/refugerestrooms/views/MainActivity.java) as a worst-case scenario.

This mess was my mistake-- I became pretty manic about certain changes and failed to take precautions to avoid this type of situation and develop changes in isolation of each other. It's been a while since I've worked on a passion project and got too excited, thanks again for helping to resolve this @DeeDeeG. I'll take more care in future to decouple my contributions and pace them reasonably.

**Comment by DeeDeeG** [comment]
> Splitting into 4 branches: master (API 28), location services, addBathroom pre-loading, and bottom sheet fixes; seems like the best way to go. They can all function separately or in tandem, with only a few easily resolvable conflicts in MainActivity.java as a worst-case scenario.

Alright, sounds perfect! :+1:

---

About the rest: No worries! Frankly, I'm excited there is a new contributor at all, much less a contributor who can keep us current and releasable on the Play Store. Neat branch structure is just a bonus.

Thanks again, sorry if it's a lot of stalling and anticipation, and hopefully we get a review from @hissingpanda. (I'll merge API 28 at least into the staging branch next week, though, even if we don't get a review by then.)

**Comment by hissingpanda** [comment]
Took a look at this just now and it looks really great! Thanks so much @Carmen-Git-It! One thing I noticed is that upon targeting API 28 we have to declare the following code in the Android manifest:

```
 <uses-library
      android:name="org.apache.http.legacy"
      android:required="false" />
```

As per: https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

I'll commit this change tomorrow.

----

The last known location is working, and the code looks great. Unfortunately I wasn't able to really look at much else as weirdly restroom markers don't seem to be populating on my phone. I didn't have time to debug this but it's happening with the current version of the play store app as well, so nothing to do with the changes. I'm using a Pixel 2 with Android 9.. Not sure if the latest Android update broke the app for me, I haven't opened it in a minute. I imagine you're not having this issue @Carmen-Git-It? What device/sdk are you on?

I'll try to debug this tomorrow night. If I'm not able to find anything immediately, I'll go ahead and merge this code anyways and release it as a beta release on the play store for the moment.

**Comment by Carmen-Git-It** [comment]
I actually just tried the app again on my phone and I'm experiencing the same issue-- I'm starting to debug it now, but it worked correctly as of a few days ago.

I'm on a Samsung Galaxy S7 with Android 8, and I've been using the app regularly without issue until today. Hopefully we find the problem!

**Comment by Carmen-Git-It** [comment]
@DeeDeeG have there been any significant changes to the RefugeRestrooms API in the last few days? I'm thinking it's either that the app is no longer accessing the db correctly, or some other dependency has changed in the last few days. I'll still be debugging for now and let you know what I find.

**Comment by DeeDeeG** [comment]
@Carmen-Git-It

Well, we did deploy recent changes that change the database structure, here: https://github.com/RefugeRestrooms/refugerestrooms/pull/531/

I also notice that when I try the API demo/documentation page here: https://refugerestrooms.org/api/docs/, I sometimes get a normal, quick response, but I sometimes get a slow response, or one that ends up just showing as "application error".

Intermittent slowness of the API, and intermittent API call failures, both apparently on the server side.

Not sure why, exactly. \*shrug\* Could be good to log into the Heroku (cloud host) instance and see the application logs.

**Comment by DeeDeeG** [comment]
We also had a rather massive "deploy"/release back on November 11th: https://github.com/RefugeRestrooms/refugerestrooms/pull/527

(I don't think anything new in this release caused the problem, though.)

Highlights/important changes:
- Updated the app from using Rails 5.1.4 --> Rails 5.2.1
- Compile all JavaScript files with WebPacker instead of Sprockets
- See also tweets in this thread:https://twitter.com/REFUGErestrooms/status/1061701144353824768
  - "longstanding geocoding bug" is to do with how we geocode new entries, shouldn't affect API users.

**Comment by DeeDeeG** [comment]
A possible non-bug explanation is people are maybe traveling for Thanksgiving about now and might be hitting the API harder than usual. But would rather exhaustively look into actual bugs than assume it's not a bug. We should theoretically be able to handle a lot of traffic with no problem.

**Comment by Carmen-Git-It** [comment]
Thanks so much for the info @DeeDeeG! I'll continue debugging it app-side to see if anything isn't working correctly there, and see what kind of reply we're getting from the server.

I'm working off of the assumption that the issue is in the app for the purposes of debugging. But I'll keep your input in mind and I'll update this thread if I find anything that stands out.

**Comment by Carmen-Git-It** [comment]
Okay I've confirmed that the issue is with the Volley (our HTTP request library) requests timing out and returning a null value to the error listener. 

You can find the error by logging the error message passed to errorListener onErrorResponse() in Server.java. 

I'll start thinking of ways around this by possibly catching local bathroom data on the phone, but it wont be a quick fix and it wont help during this period of null responses.

We could change the default timeout on Volley, but that may decrease the quality of the user experience when the server isn't just slow.

**Comment by Carmen-Git-It** [comment]
Markers are loading perfectly with a small change to the Json Array Request code in RequestHandler.java, changing the default timeout from 5 seconds to 12 seconds. :)

**Comment by DeeDeeG** [comment]
:tada:

**Pull request merged**
